# Generated by Django 4.1.4 on 2022-12-09 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'movie',
                'verbose_name_plural': 'movies',
                'db_table': 'movie',
            },
        ),
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'people',
                'db_table': 'person',
            },
        ),
        migrations.CreateModel(
            name='Average',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average', models.FloatField()),
                ('id_movie', models.ForeignKey(db_column='id_movie', on_delete=django.db.models.deletion.CASCADE, to='control.movie', verbose_name='movie')),
                ('id_person', models.ForeignKey(db_column='id_person', on_delete=django.db.models.deletion.CASCADE, to='control.person', verbose_name='person')),
            ],
            options={
                'verbose_name': 'average',
                'verbose_name_plural': 'averages',
                'db_table': 'average',
            },
        ),
    ]
